AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create complete CI/CD using AWS CodeCommit, CodePipeline, CodeBuild and
  CodeDeploy - Example
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: 'CodeCommit configuration (to build CodeCommit repository):'
        Parameters:
          - CodeCommitWebAppRepo
          - CodeCommitMainBranchName
      - Label:
          default: 'CodeBuild configuration (to build CodeBuild environment):'
        Parameters:
          - CodeBuildProjectName
      - Label:
          default: 'CodeDeploy configuration (to create CodeDeploy App & Group):'
        Parameters:
          - CodeDeployApp
          - CodeDeployGroup
          - CodeDeployGroupTagKey
          - CodeDeployGroupTagValue
          - CodeDeployConfigName
      - Label:
          default: 'CodePipeline configuration (to build a 4 stage CodePipeline):'
        Parameters:
          - CodePipelineName
          - CodePipelineArtifactS3Bucket
Parameters:
  CodeCommitWebAppRepo:
    Type: String
    Default: MyWebAppRepo
    Description: Enter name of the new CodeCommit Repo for your Web App.
  CodeCommitMainBranchName:
    Type: String
    Default: master
    Description: Enter main branch name on your CodeCommit repository. Default is master.
  CodeBuildProjectName:
    Type: String
    Default: MyCBWebAppProject
    Description: Enter name of the new CodeBuild environment.
  CodeDeployApp:
    Type: String
    Default: MyCDWebApp
    Description: Enter name of the new CodeDeploy App to be created for your Web App.
  CodeDeployGroup:
    Type: String
    Default: MyCICD-Deployment-Group
    Description: >-
      Enter name of the new CodeDeploy Deployment Group to be created in AWS
      account.
  CodeDeployGroupTagKey:
    Type: String
    Default: Application
    Description: >-
      Enter Tag Key that will be used by CodeDeploy to identify the existing EC2
      fleet to be used by the Deployment Group.
  CodeDeployGroupTagValue:
    Type: String
    Default: MyWebApp
    Description: >-
      Enter Tag Value that will be used by CodeDeploy to identify the existing
      EC2 fleet to be used by the Deployment Group.
  CodeDeployConfigName:
    Type: String
    Default: CodeDeployDefault.OneAtATime
    AllowedValues:
      - CodeDeployDefault.OneAtATime
      - CodeDeployDefault.HalfAtATime
      - CodeDeployDefault.AllAtOnce
    Description: >-
      Enter desired Code Deploy Config Name. Default is:
      CodeDeployDefault.OneAtATime.
  CodePipelineName:
    Type: String
    Default: MyWebAppPipeline
    Description: Enter name of the new CodePipeline to be created for your Web App.
  CodePipelineArtifactS3Bucket:
    Type: String
    Default: ''
    Description: >-
      Enter name of the new Amazon S3 bucket to be created where artifacts for
      the pipeline are stored for this web app. Ex:
      mywebapp-codepipeline-bucket-us-east-1-111111111111. 
Resources:
  myKMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: An example of symmetric CMK
      KeyPolicy:
        Version: 2012-10-17
        Id: kms-key-policy
        Statement:
          - Sid: >-
              Allow access through Amazon S3 for all principals in the account
              that are authorized to use Amazon S3
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
            Condition:
              StringEquals:
                'kms:CallerAccount': !Sub '${AWS::AccountId}'
                'kms:ViaService': !Sub 's3.${AWS::Region}.amazonaws.com'
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt [CodePipelineServiceRole, Arn]
                - !GetAtt [CodeBuildServiceRole, Arn]
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
  myKMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: alias/MyCICDKey
      TargetKeyId: !Ref myKMSKey
  myS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref CodePipelineArtifactS3Bucket
  myS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref myS3Bucket
      PolicyDocument:
        Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${CodePipelineArtifactS3Bucket}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': !Sub '${AWS::Partition}:kms'
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${CodePipelineArtifactS3Bucket}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
  MyWebAppRepo:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: !Ref CodeCommitWebAppRepo
      RepositoryDescription: A sample web application application
  CodeBuildProject:
    Type: 'AWS::CodeBuild::Project'
    DependsOn: MyWebAppRepo
    Properties:
      Name: !Ref CodeBuildProjectName
      Description: This is sample web app project
      ServiceRole: !GetAtt [CodeBuildServiceRole, Arn]
      Artifacts:
        Type: S3
        Location: !Ref CodePipelineArtifactS3Bucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:3.0-19.11.26'
        EnvironmentVariables: []
      Source:
        Location: !GetAtt 
          - MyWebAppRepo
          - CloneUrlHttp
        Type: CODECOMMIT
      TimeoutInMinutes: 30
      Tags:
        - Key: Role
          Value: MyJavaApp
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement: 
            - 
              Effect: "Allow"
              Principal: 
                Service: 
                  - "codebuild.amazonaws.com"
              Action: 
                - "sts:AssumeRole"
        Path: "/"
        Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowBuildOutputStreamingToDefaultLogGroup
              Effect: Allow
              Resource:
              - arn:aws:logs:*:*:log-group:*
              Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            - Sid: AllowS3ObjectAccessOnCodePipelineBuckets
              Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:GetBucketAcl
              - s3:GetBucketLocation
              Resource: "*"
              Effect: Allow
            - Sid: AllowPullSourceCodeFromCodeCommit
              Action: codecommit:GitPull
              Resource: "*"
              Effect: Allow
            - Sid: AllowPushDockerImageToECR
              Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:CompleteLayerUpload
              - ecr:GetAuthorizationToken
              - ecr:InitiateLayerUpload
              - ecr:PutImage
              - ecr:UploadLayerPart
              Resource: "*"
              Effect: Allow
            - Sid: AllowAccessCodeBuildSSMParameters
              Effect: Allow
              Action: ssm:GetParameters
              Resource: arn:aws:ssm:*:*:parameter/CodeBuild/*
            - Sid: AllowRunningBuildInVpc
              Effect: Allow
              Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeDhcpOptions
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
              - ec2:DescribeSubnets
              - ec2:DescribeSecurityGroups
              - ec2:DescribeVpcs
              Resource: "*"
            - Sid: AllowBuildServiceToCreateENI
              Effect: Allow
              Action: ec2:CreateNetworkInterfacePermission
              Resource: arn:aws:ec2:*:*:network-interface/*
              Condition:
                StringEquals:
                  ec2:AuthorizedService: codebuild.amazonaws.com
          PolicyName: CodeBuildServiceRole
  MyCodeDeployApp:
    Type: 'AWS::CodeDeploy::Application'
    Properties:
      ApplicationName: !Ref CodeDeployApp
  DeploymentGroup:
    Type: 'AWS::CodeDeploy::DeploymentGroup'
    Properties:
      ApplicationName: !Ref MyCodeDeployApp
      DeploymentGroupName: !Ref CodeDeployGroup
      DeploymentConfigName: !Ref CodeDeployConfigName
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
          - DEPLOYMENT_STOP_ON_ALARM
          - DEPLOYMENT_STOP_ON_REQUEST
      ServiceRoleArn: !GetAtt [CodeDeployServiceRole, Arn]
      Ec2TagFilters:
        - Key: !Ref CodeDeployGroupTagKey
          Value: !Ref CodeDeployGroupTagValue
          Type: KEY_AND_VALUE
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codedeploy.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole"
  MyCodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Ref CodePipelineName
      RoleArn: !GetAtt  [CodePipelineServiceRole, Arn]
      Stages:
        - Name: Source
          Actions:
            - Name: ApplicationSource
              ActionTypeId:
                Version: '1'
                Category: Source
                Owner: AWS
                Provider: CodeCommit
              OutputArtifacts:
                - Name: WebAppRepo-SourceArtifact
              Configuration:
                RepositoryName: !Ref CodeCommitWebAppRepo
                BranchName: !Ref CodeCommitMainBranchName
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: ApplicationBuild
              InputArtifacts:
                - Name: WebAppRepo-SourceArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: WebAppRepo-BuiltArtifact
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 2
        - Name: Deploy
          Actions:
            - Name: Deploy
              InputArtifacts:
                - Name: WebAppRepo-SourceArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CodeDeploy
              Configuration:
                ApplicationName: !Ref CodeDeployApp
                DeploymentGroupName: !Ref CodeDeployGroup
              RunOrder: 3
      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineArtifactS3Bucket
        EncryptionKey:
          Id: !GetAtt 
            - myKMSKey
            - Arn
          Type: KMS
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "codecommit.amazonaws.com"
                - "codepipeline.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyDocument:
            Statement:
            - Action:
              - iam:PassRole
              Resource: "*"
              Effect: Allow
              Condition:
                StringEqualsIfExists:
                  iam:PassedToService:
                  - cloudformation.amazonaws.com
                  - elasticbeanstalk.amazonaws.com
                  - ec2.amazonaws.com
                  - ecs-tasks.amazonaws.com
            - Action:
              - codecommit:CancelUploadArchive
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetRepository
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
              Resource: "*"
              Effect: Allow
            - Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetApplication
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
              Resource: "*"
              Effect: Allow
            - Action:
              - codestar-connections:UseConnection
              Resource: "*"
              Effect: Allow
            - Action:
              - elasticbeanstalk:*
              - ec2:*
              - elasticloadbalancing:*
              - autoscaling:*
              - cloudwatch:*
              - s3:*
              - sns:*
              - cloudformation:*
              - rds:*
              - sqs:*
              - ecs:*
              Resource: "*"
              Effect: Allow
            - Action:
              - lambda:InvokeFunction
              - lambda:ListFunctions
              Resource: "*"
              Effect: Allow
            - Action:
              - opsworks:CreateDeployment
              - opsworks:DescribeApps
              - opsworks:DescribeCommands
              - opsworks:DescribeDeployments
              - opsworks:DescribeInstances
              - opsworks:DescribeStacks
              - opsworks:UpdateApp
              - opsworks:UpdateStack
              Resource: "*"
              Effect: Allow
            - Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
              Resource: "*"
              Effect: Allow
            - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:BatchGetBuildBatches
              - codebuild:StartBuildBatch
              Resource: "*"
              Effect: Allow
            - Effect: Allow
              Action:
              - devicefarm:ListProjects
              - devicefarm:ListDevicePools
              - devicefarm:GetRun
              - devicefarm:GetUpload
              - devicefarm:CreateUpload
              - devicefarm:ScheduleRun
              Resource: "*"
            - Effect: Allow
              Action:
              - servicecatalog:ListProvisioningArtifacts
              - servicecatalog:CreateProvisioningArtifact
              - servicecatalog:DescribeProvisioningArtifact
              - servicecatalog:DeleteProvisioningArtifact
              - servicecatalog:UpdateProduct
              Resource: "*"
            - Effect: Allow
              Action:
              - cloudformation:ValidateTemplate
              Resource: "*"
            - Effect: Allow
              Action:
              - ecr:DescribeImages
              Resource: "*"
            - Effect: Allow
              Action:
              - states:DescribeExecution
              - states:DescribeStateMachine
              - states:StartExecution
              Resource: "*"
            - Effect: Allow
              Action:
              - appconfig:StartDeployment
              - appconfig:StopDeployment
              - appconfig:GetDeployment
              Resource: "*"
            Version: '2012-10-17'
          PolicyName: CodePipelineServiceRole
  CloudWatchEventRuleMasterPipeline:
    Type: 'AWS::Events::Rule'
    Properties:
      Name: !Ref CodePipelineName
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources:
          - !Join 
            - ''
            - - 'arn:'
              - !Ref 'AWS::Partition'
              - ':codecommit:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref CodeCommitWebAppRepo
        detail:
          event:
            - referenceCreated
            - referenceUpdated
          referenceType:
            - branch
          referenceName:
            - !Ref CodeCommitMainBranchName
      Targets:
        - Arn: !Join 
            - ''
            - - 'arn:'
              - !Ref 'AWS::Partition'
              - ':codepipeline:'
              - !Ref 'AWS::Region'
              - ':'
              - !Ref 'AWS::AccountId'
              - ':'
              - !Ref CodePipelineName
          RoleArn: !GetAtt  [CodePipelineCWEventTriggerRole, Arn]
          Id: codepipeline-AppPipeline
  CodePipelineCWEventTriggerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "events.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - codepipeline:StartPipelineExecution
              Resource:
              - !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:*'
          PolicyName: CodePipelineCWEventRole
Outputs:
  MyCodePipelineName:
    Description: My CI/CD Pipeline
    Value: !Ref MyCodePipeline
  MyCodeCommitHttpUrl:
    Description: My CodeCommit Repository Http Url
    Value: !GetAtt 
      - MyWebAppRepo
      - CloneUrlHttp
